### ISSUE TITLE
Create coafile

### ISSUE THREAD

**Issue by sils** [viper-development/legal#2]

**Comment by sils** [comment]
@coafile

**Comment by coafile** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by coafile** [comment]
```# Generated by coala-quickstart on 25 Jul 2017.
[default]
bears = LineCountBear, InvalidLinkBear, FilenameBear
files = **.md
[markdown]
bears = LineLengthBear, SpaceConsistencyBear, KeywordBear, LicenseCheckBear, DuplicateFileBear, MarkdownBear, coalaBear
files = **.md
```

**Comment by coafile** [comment]
coafile creation process Successful! :tada: :tada: :tada:


 Next Steps: 

 Step 1: Merge the Pull Request https://github.com/viper-development/legal/pull/3 having the .coafile.
 Step 2: Turn on [GitMate](https://gitmate.io) Integration on this repository.
 Step 3: Turn on code analysis for automated code reviews on your PRs.

 Happy Linting! :tada:
